server:
  port: 10004

spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: dw
    password: 1111
  servlet:
    multipart:
      enabled: true
      max-file-size: 40MB
      max-request-size: 40MB
      file-size-threshold: 100MB
  jpa:
    hibernate:
      ddl-auto: create
#      ddl-auto: create-drop
#      ddl-auto: update
#      ddl-auto: validate

    properties:
      hibernate:
#        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000 #최적화 옵션

logging.level:
  org.hibernate.SQL: debug

#  org.hibernate.type: trace

# 파일 경로 설정
file.dir: C:/jpa_dw/goods

  # 문자인증
#  smsservice.accessKey = oyEpUB0ISONyYhRS0eoF
#  smsservice.secretKey = 6VE8paDtAxkpEJOkOAIlJoKzwvbfZalNDzzUq1M5


